# Generated by Django 4.1.5 on 2023-01-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
